name: Run RSpec Tests
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
      run:
        bundle exec rspec
