name: Run RSpec Tests
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          run:
            bundle exec rspec